[vault]
# it's recommended to use absolute paths to allow the program
# to properly launch the correct file.
dir = "./vaults"

# paths are relative to the vault dir
[periodical.day]
dir = "periodic/day"
template = "templates/day.md"

[periodical.week]
dir = "periodic/week"

[periodical.month]
dir = "periodic/monthly"
template = "templates/month.md"

[periodical.year]
dir = "periodic/year"
